### ISSUE TITLE
Not working on mac os

### ISSUE THREAD

**Issue by mgomma** [carlosreig/docker-lamp#21] opened 2019-09-02 13:18 UTC
starting the container enters a loop on trying to install packages.
Below messages from terminal.

$ ./start.sh 
Building web
Step 1/9 : FROM php:7.3-apache-stretch
 ---> 140355f5aa2b
Step 2/9 : RUN useradd -u 1000 -m www-bridge-user
 ---> Using cache
 ---> 118681a80d1d
Step 3/9 : RUN apt-get update
 ---> Using cache
 ---> 2903a43ceb8f
Step 4/9 : RUN apt-get install -y   git   wget   zlib1g-dev   zip   vim   mysql-client   libpng-dev   libmcrypt-dev   libicu-dev   nodejs   libzip-dev   libfreetype6-dev   libjpeg62-turbo-dev   gnupg2   ssmtp &&   pecl install mcrypt-1.0.2 &&   apt-get install -y libmagickwand-dev --no-install-recommends &&   docker-php-ext-install mbstring &&   docker-php-ext-install pdo_mysql &&   docker-php-ext-install mysqli &&   docker-php-ext-enable mcrypt &&   docker-php-ext-install opcache &&   docker-php-ext-install pcntl &&   docker-php-ext-install intl &&   docker-php-ext-install zip &&   docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ &&   docker-php-ext-install gd &&   pecl install imagick &&   docker-php-ext-enable imagick &&   rm -r /var/lib/apt/lists/* &&   curl -sS https://getcomposer.org/installer | php &&   mv composer.phar /usr/bin/composer &&   pecl install xdebug &&   a2enmod rewrite &&   a2enmod ssl &&   a2ensite default-ssl &&   curl -sL https://deb.nodesource.com/setup_12.x | bash -
 ---> Running in dc93757f045b
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  default-mysql-client dirmngr git-man gnupg gnupg-agent gnupg-l10n
  icu-devtools less libaio1 libassuan0 libconfig-inifiles-perl libcurl3-gnutls
  libdbd-mysql-perl libdbi-perl liberror-perl libfreetype6 libgnutls-openssl27
  libgpm2 libjemalloc1 libjpeg62-turbo libksba8 libmariadbclient18 libmcrypt4
  libnpth0 libpng-tools libpng16-16 libpopt0 libreadline5 libreadline7
  libterm-readkey-perl libuv1 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6
  libxext6 libxmuu1 libzip4 mariadb-client-10.1 mariadb-client-core-10.1
  mariadb-common mysql-common openssh-client pinentry-curses readline-common
  rsync unzip vim-common vim-runtime xauth xxd
Suggested packages:
  dbus-user-session libpam-systemd pinentry-gnome3 tor gettext-base
  git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk
  gitweb git-arch git-cvs git-mediawiki git-svn parcimonie xloadimage scdaemon
  libclone-perl libmldbm-perl libnet-daemon-perl libsql-statement-perl gpm
  icu-doc mcrypt keychain libpam-ssh monkeysphere ssh-askpass pinentry-doc
  readline-doc openssh-server ctags vim-doc vim-scripts
The following NEW packages will be installed:
  default-mysql-client dirmngr git git-man gnupg gnupg-agent gnupg-l10n gnupg2
  icu-devtools less libaio1 libassuan0 libconfig-inifiles-perl libcurl3-gnutls
  libdbd-mysql-perl libdbi-perl liberror-perl libfreetype6 libfreetype6-dev
  libgnutls-openssl27 libgpm2 libicu-dev libjemalloc1 libjpeg62-turbo
  libjpeg62-turbo-dev libksba8 libmariadbclient18 libmcrypt-dev libmcrypt4
  libnpth0 libpng-dev libpng-tools libpng16-16 libpopt0 libreadline5
  libreadline7 libterm-readkey-perl libuv1 libx11-6 libx11-data libxau6
  libxcb1 libxdmcp6 libxext6 libxmuu1 libzip-dev libzip4 mariadb-client-10.1
  mariadb-client-core-10.1 mariadb-common mysql-client mysql-common nodejs
  openssh-client pinentry-curses readline-common rsync ssmtp unzip vim
  vim-common vim-runtime wget xauth xxd zip zlib1g-dev
0 upgraded, 67 newly installed, 0 to remove and 6 not upgraded.
Need to get 61.7 MB of archives.
After this operation, 289 MB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 libcurl3-gnutls amd64 7.52.1-5+deb9u9 [290 kB]
Get:28 http://security-cdn.debian.org/debian-security stretch/updates/main amd64 xxd amd64 2:8.0.0197-4+deb9u3 [132 kB]

**Comment by carlosreig** [comment] 2019-09-09 08:54
Hi @mgomma 

Thanks for the report but I don't work with Mac OS so I cannot reproduce the problem. Let see if someone can.

**Comment by c50** [comment] 2019-12-12 13:17
Hi @mgomma, @carlosreig I am currently running this on MacOs Mojave 10.14.6 (16Gb RAM), with Docker Desktop Community 2.1.0.4, and no problem so far.

**Comment by carlosreig** [comment] 2019-12-12 13:33
Thanks @c50 .

I'll close the issue. Also, if you have any feedback about the project, feel free to share :)

**Closed as completed by carlosreig** 2019-12-12 13:33 UTC
